name: multimodal-search
channels:
  - huggingface
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - pip
  - ipykernel
  - gradio
  - pytorch
  - iprogress
  - pillow
  - torchvision
  - pip:
    - transformers
    - diffusers
    - datasets
    - accelerate
    - faiss-cpu
    - sentence-transformers
    - git+https://github.com/huggingface/transformers